version: '3.9'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: sh -c "[ \"$NODE_ENV\" = \"development\" ] && npm run dev || npm start"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
